# -*- coding: utf-8 -*-
"""Matplotlib and seaborn on Universities.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQ5NPexaOuBkkdtnx_lw3qPZy8cnxNfh
"""

import matplotlib.pyplot as plt

import pandas as pd

"""`import matplotlib.pyplot as plt` is a common line of code in Python used for data visualization. Here's a breakdown of what it means:

*   **`import matplotlib.pyplot`**: This imports the `pyplot` module from the `matplotlib` library. `matplotlib` is a widely used plotting library in Python, and `pyplot` provides a collection of functions that make `matplotlib` work like MATLAB.

*   **`as plt`**: This creates an *alias* for `matplotlib.pyplot`. Instead of typing `matplotlib.pyplot` every time you want to use one of its functions, you can simply type `plt`. This is a common convention that makes the code shorter and more readable.

In short, this line of code allows you to create various types of plots and charts in Python with a simple and intuitive interface.
"""

import seaborn as sns

df=pd.read_csv('Universities.csv')

df

plt.hist(df['SAT'])

plt.hist(df['SAT'])
plt.xlabel('SAT SCORES')
plt.ylabel('Frequency')
plt.title('Histogram of SAT Scores vs Frequency')
plt.show()

sns.histplot(df['SAT'],color='orange')
plt.show()

plt.plot(df['Top10'],df['Accept'],'go')
plt.xlabel('Top10')
plt.ylabel('Acceptance')
plt.title('Scatter plot of Top10 vs Acceptance')
plt.show()

plt.scatter(df['SAT'],df['Accept'])
plt.xlabel('SAT Score')
plt.ylabel('Acceptance')
plt.title('Scatter plot of SAT Score vs Acceptance')
plt.show()

sns.pairplot(df)

sns.pairplot(df.iloc[:,1:3])

plt.boxplot(df['SAT'])
plt.show()

